# Generated by Django 3.2.16 on 2023-12-04 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_unique person constraint'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='post',
            name='Unique person constraint',
        ),
    ]
