# Generated by Django 3.2.16 on 2024-02-01 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_delete_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
